/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2020-05-05 10:05:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.bean.ChiTietHoaDonBEAN;
import model.bean.HoaDonBEAN;
import java.util.ArrayList;
import java.text.DecimalFormat;

public final class DanhSachHoaDon_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/admin/Header.jsp", Long.valueOf(1588065743004L));
    _jspx_dependants.put("/admin/Footer.jsp", Long.valueOf(1588084243331L));
    _jspx_dependants.put("/admin/Nav.jsp", Long.valueOf(1588083378582L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.bean.ChiTietHoaDonBEAN");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("model.bean.HoaDonBEAN");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/png\" href=\"image/favicon.ico\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Admin-KhoSach</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template-->\r\n");
      out.write("<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Page level plugin CSS-->\r\n");
      out.write("<link href=\"vendor/datatables/dataTables.bootstrap4.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template-->\r\n");
      out.write("<link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/css.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand navbar-dark bg-white static-top\"\r\n");
      out.write("\tstyle=\"box-shadow: 0 .15rem 1.75rem 0 rgba(58, 59, 69, .15) !important;\">\r\n");
      out.write("\r\n");
      out.write("\t<a class=\"navbar-brand mr-1\" href=\"index.html\"><img\r\n");
      out.write("\t\tsrc=\"image/logo.png\" alt=\"\" style=\"width: 212px;\"></a>\r\n");
      out.write("\r\n");
      out.write("\t<button class=\"btn btn-link btn-sm text-white order-1 order-sm-0\"\r\n");
      out.write("\t\tid=\"sidebarToggle\" href=\"#\" style=\"background: #000\">\r\n");
      out.write("\t\t<i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t</button>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navbar Search -->\r\n");
      out.write("\t<form\r\n");
      out.write("\t\tclass=\"d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0\">\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navbar -->\r\n");
      out.write("\t<ul class=\"navbar-nav ml-auto ml-md-0\">\r\n");
      out.write("\t\t<li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("\t\t\t<div style=\"display: inline-flex;\">\r\n");
      out.write("\t\t\t");
 DecimalFormat formatter = new DecimalFormat("###,###,###.00");
				String tenAdmin = (String) session.getAttribute("txtTenDangNhap"); 
      out.write("\r\n");
      out.write("\t\t\t\t<h5 style=\"padding-top: 5px; padding-right: 30px; color: #000;\">\r\n");
      out.write("\t\t\t\t\tXin chào ");
      out.print(tenAdmin );
      out.write(" <i class=\"fas fa-user-circle fa-fw\"></i>\r\n");
      out.write("\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\"\r\n");
      out.write("\t\t\t\t\t\trole=\"button\" style=\"color: #000\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-cog\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"userDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Cài đặt</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Thông tin admin</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t   <a class=\"dropdown-item\" href=\"DangXuatAdminSevlet\" >Đăng xuất</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Sidebar -->\r\n");
      out.write("\t<ul class=\"sidebar navbar-nav\">\r\n");
      out.write("\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.php\">\r\n");
      out.write("\t\t\t\t<i class=\"fas fa-fw fa-tachometer-alt\"></i> <span>Trang chủ</span>\r\n");
      out.write("\t\t</a></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-list\"></i> <span> Danh mục</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Quản lý danh mục</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"ThemDanhMucServlet\">Thêm danh mục</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"DanhMucServlet\">Danh sách danh\r\n");
      out.write("\t\t\t\t\tmục</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span> Nhóm Thể loại</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Quản lý nhóm thể loại</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"ThemNhomTheLoaiServlet\">Thêm nhóm\r\n");
      out.write("\t\t\t\t\tthể loại</a> <a class=\"dropdown-item\" href=\"NhomTheLoaiServlet\">Danh\r\n");
      out.write("\t\t\t\t\tsách nhóm <br> thể loại</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span> Thể loại</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Quản lý thể loại</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"ThemTheLoaiServlet\">Thêm thể loại</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"TheLoaiServlet\">Danh sách thể\r\n");
      out.write("\t\t\t\t\tloại</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-book\"></i> <span> Sách</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Quản lý sách</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"ThemSachServlet\">Thêm sách</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-item\" href=\"SachServlet\">Danh sách sách</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-file-alt\"></i> <span> Đơn hàng</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Quản lý đơn hàng</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"DanhSachHoaDonSevlet\">Danh sách đơn hàng</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-users\"></i> <span> Khách hàng</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Quản lý khách hàng</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"DanhSachKhachHangServlet\">Danh sách khách hàng</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fa fa-comment\" aria-hidden=\"true\"></i> <span> Bình luận</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Quản lý Bình luận</h6>\r\n");
      out.write("\t\t\t\t <a class=\"dropdown-item\" href=\"DanhSachSachBinhLuanServlet\">Danh sách bình luận</a>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-user-alt\"></i> <span> Admin</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Quản lý admin</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"ThemAdminSevlet\">Thêm admin</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-item\" href=\"DanhSachAdminSevlet\">Danh sách admin</a>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("\t\t\thref=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-paste\"></i> <span> Thống kê</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Thông kế</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"ThongKeTheoNamServlet\">Số lượng hóa đơn <br> trong năm</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"ThongKeDoanhThuTheoNamServlet\">Doanh thu <br> trong năm</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"BieuDoDanhThuTheoNam\">Biểu đồ doanh thu</a>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"content-wrapper\"\r\n");
      out.write("\t\tstyle=\"background: #f1f1f1; margin-bottom: 40px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container-fluid\">");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row shadow\">\r\n");
      out.write("\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t<div class=\"px-2\">\r\n");
      out.write("\t\t\t\t<h4 class=\"title mt-4 mb-5 text-center text-uppercase text-danger\">Danh Sách Hóa Đơn</h4>\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
int maHoaDon =0; 
      out.write("\r\n");
      out.write("\t <div class=\"card shadow mb-4\">\r\n");
      out.write("\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t<div class=\"table-responsive table-hover\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\"\tcellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Mã hóa đơn</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Mã khách hàng</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Trạng thái</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Ngày lập</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Phương thức thanh toán</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
String phuongThuc,trangThai,txtDuyet;
					ArrayList<HoaDonBEAN> listHoaDon = (ArrayList<HoaDonBEAN>)request.getAttribute("listHoaDon");
					for(HoaDonBEAN hoaDon: listHoaDon){
						maHoaDon =hoaDon.getMaHoaDon();
						if(hoaDon.isTrangThai()==1)	{
						    trangThai="Đã duyệt";
						}
						else if(hoaDon.isTrangThai()==2){
						    trangThai="Trả đơn";
						}else{
						    trangThai = "Chưa duyệt";
						    }
						if(hoaDon.getPhuongThucThanhToan()==1) phuongThuc="Thanh toán khi nhận hàng";
						else phuongThuc="Thanh toán qua thẻ";
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"trXoaDonHang");
      out.print(hoaDon.getMaHoaDon());
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(hoaDon.getMaHoaDon() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(hoaDon.getMaKhachHang() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td id=\"trangThai");
      out.print(hoaDon.getMaHoaDon());
      out.write('"');
      out.write('>');
      out.print(trangThai);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(hoaDon.getNgayLap() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(phuongThuc );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a style=\"margin-right: 3px;\"  class=\"btn btn-info\" onclick=\"clickChiTiet(");
      out.print(hoaDon.getMaHoaDon() );
      out.write(")\" data-toggle=\"modal\" data-target=\"#chiTiet");
      out.print(maHoaDon);
      out.write("\"><i class=\"fas fa-info-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a style=\"margin-right: 3px;\" class=\"btn btn-danger\" onclick=\"deleteRow(");
      out.print(hoaDon.getMaHoaDon() );
      out.write(")\" name=\"btnXoa\" ><i class=\"fas fa-trash-alt\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a style=\"margin-right: 3px;\" class=\"btn btn-success\" onclick=\"clickDuyet(");
      out.print(hoaDon.getMaHoaDon() );
      out.write(")\" ><i class=\"fas fa-check-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-warning\" onclick=\"clickTraDon(");
      out.print(hoaDon.getMaHoaDon() );
      out.write(")\" ><i class=\"fas fa-undo-alt\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
for(HoaDonBEAN ctHoaDon: listHoaDon){ 
      out.write("\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"chiTiet");
      out.print(ctHoaDon.getMaHoaDon() );
      out.write("\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t\t\t        <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t            <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t            \t<h4 class=\"modal-title\" id=\"myModalLabel\">Chi tiết hóa đơn</h4>\r\n");
      out.write("\t\t\t\t                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t                </button>                 \r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t            <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t                <table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t                    <thead>\r\n");
      out.write("\t\t\t\t                        <tr>\r\n");
      out.write("\t\t\t\t                            <th>Mã hóa đơn</th>\r\n");
      out.write("\t\t\t\t                            <th>Mã sách</th>\r\n");
      out.write("\t\t\t\t                            <th>Tên sách</th>\r\n");
      out.write("\t\t\t\t                            <th>Ảnh</th>\r\n");
      out.write("\t\t\t\t                            <th>Số lượng</th>\r\n");
      out.write("\t\t\t\t                            <th>Giá</th>\r\n");
      out.write("\t\t\t\t                            <th>Tổng tiền</th>\r\n");
      out.write("\t\t\t\t                        </tr>\r\n");
      out.write("\t\t\t\t                    </thead>\r\n");
      out.write("\t\t\t\t                    <tbody id=\"trChiTiet");
      out.print(ctHoaDon.getMaHoaDon());
      out.write("\">\r\n");
      out.write("\t\t\t\t                    </tbody>\r\n");
      out.write("\t\t\t\t                </table>\r\n");
      out.write("\t\t\t\t               \r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t            <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</div>");
} 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<footer class=\"sticky-footer\" style=\"background: #fff; color: #000\">\r\n");
      out.write("\t<div class=\"container my-auto\">\r\n");
      out.write("\t\t<div class=\"copyright text-center my-auto\">\r\n");
      out.write("\t\t\t<p style=\"font-size: 12px; text-align: center; padding-top: 24px;\">Khosach.com</p>\r\n");
      out.write("\t\t\t<p style=\"text-align: center; font-size: 12px;\">Copyright &copy;\r\n");
      out.write("\t\t\t\tFsoftTeamHue2020</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Bootstrap core JavaScript-->\r\n");
      out.write("<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Core plugin JavaScript-->\r\n");
      out.write("<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Page level plugin JavaScript-->\r\n");
      out.write("<script src=\"vendor/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"vendor/datatables/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom scripts for all pages-->\r\n");
      out.write("<script src=\"js/sb-admin.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Demo scripts for this page-->\r\n");
      out.write("<script src=\"js/demo/datatables-demo.js\"></script>\r\n");
      out.write("<!-- <script src=\"https://cdn.tiny.cloud/1/zwvnvg1vtpffr9njh0ifh6avwyc1gp7j7amjt0enupkam7r5/tinymce/5/tinymce.min.js\"></script>\r\n");
      out.write("  <script>tinymce.init({selector:'textarea'});</script> -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/search.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/thongke.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/doanhthu.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/chiTietHoaDon.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/duyetDon.js\"></script>\r\n");
      out.write("<script src=\"js/huydonhang.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/xoaSach.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bieudodoanhthu.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/danhsachbinhluan.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"ckeditor/ckeditor.js\"\r\n");
      out.write("\tcharset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    config ={};\r\n");
      out.write("    config.entities = false;\r\n");
      out.write("    config.basicEntities = false;\r\n");
      out.write("    config.entities_latin=false;\r\n");
      out.write("    config.language='vi';\r\n");
      out.write("    CKEDITOR.replace('content',{\r\n");
      out.write("      filebrowserUploadUrl: 'ckeditor/ck_upload.php',\r\n");
      out.write("      filebrowserUploadMethod: 'form'\r\n");
      out.write("    },config);\r\n");
      out.write("  </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
