/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2020-04-29 07:06:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.bean.GioHangBEAN;
import java.util.ArrayList;
import java.text.DecimalFormat;
import model.bean.TheLoaiBEAN;
import model.bean.NhomTheLoaiBEAN;
import model.bean.DanhMucBEAN;
import model.bean.KhachHangBEAN;
import model.bean.GioHangBEAN;
import java.util.ArrayList;

public final class GioHang_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DangNhap.jsp", Long.valueOf(1587994023441L));
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1588134225292L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1588070292035L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.bean.KhachHangBEAN");
    _jspx_imports_classes.add("model.bean.DanhMucBEAN");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("model.bean.TheLoaiBEAN");
    _jspx_imports_classes.add("model.bean.NhomTheLoaiBEAN");
    _jspx_imports_classes.add("model.bean.GioHangBEAN");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Kho sách</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/png\" href=\"image/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/meanmenu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/css.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/dangnhap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/styleheader2.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\"#myScroll\" data-offset=\"50\">\r\n");
      out.write("\t");

				DecimalFormat formatter = new DecimalFormat("###,###,###.00");
				ArrayList<DanhMucBEAN> danhMucBean = (ArrayList<DanhMucBEAN>)request.getAttribute("listDanhMuc");
				ArrayList<NhomTheLoaiBEAN> nhomTheLoaiBean = (ArrayList<NhomTheLoaiBEAN>)request.getAttribute("listNhomTheLoai");
				ArrayList<TheLoaiBEAN> theLoaiBean = (ArrayList<TheLoaiBEAN>)request.getAttribute("listTheLoai");
		
      out.write('\r');
      out.write('\n');
      out.write('	');

	    ArrayList<GioHangBEAN> gio = (ArrayList<GioHangBEAN>) session.getAttribute("gio");
						    KhachHangBEAN kh = (KhachHangBEAN) session.getAttribute("KhachHang");
														    Long TongTien=(long)0;
	
      out.write("\r\n");
      out.write("\t<!-- header -->\r\n");
      out.write("\t<header class=\"header__container\">\r\n");
      out.write("\t\t<div class=\"header__wrapper js-container\" style=\"padding-top: 20px\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"header__left-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header__wrapper-left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header__logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"> <img src=\"image/logo.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header__form\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"Timkiem\" method=\"GET\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"header__form-input\" id=\"search\" name=\"search\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Hôm nay bạn muốn tìm ....\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"header__form-submit\" required>Tìm\r\n");
      out.write("\t\t\t\t\t\t\t\t\tkiếm</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<div  class=\"resutlSearch\">\r\n");
      out.write("                                <ul class=\"menu-search\" id=\"resutlSearch\">\r\n");
      out.write("                               \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"header__wrapper-right\">\r\n");
      out.write("\t\t\t\t\t\t");

						    if(session.getAttribute("KhachHang")!=null){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a class=\"header__wrapper-link\" style=\"margin-top: 4px\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-user\"></i> Xin chào ");
      out.print(kh.getTenKhachHang());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t");

						    }else{
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a id=\"myBtn\" class=\"header__wrapper-link\" style=\"margin-top: 4px;cursor: pointer;\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-user\"></i> Tài khoản\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t");

						    }
						
      out.write("</a> <a href=\"\" class=\"header__wrapper-link\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-bell\"></i> Thông báo\r\n");
      out.write("\t\t\t\t\t\t</a> <a href=\"Giohang\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"header__wrapper-link shopping__cart-icon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i> <span id=\"SLG\" class=\"number__cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									int soLuongSP=0;
									for(GioHangBEAN ghang : gio){
										soLuongSP += ghang.getSoLuong();
									}
								    if(gio == null) out.print("0");else out.print(soLuongSP);
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"header__middle\">\r\n");
      out.write("\t\t\t\t<div class=\"header__category\" id=\"headingOne\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"header__category-name\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#demo\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-align-right header__category-icon\"></i> Danh mục sản\r\n");
      out.write("\t\t\t\t\t\tphẩm\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"header__category-list collapse\" id=\"demo\">\r\n");
      out.write("\t\t\t\t\t\t");

							for (DanhMucBEAN danhMuc : danhMucBean) {
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"header__category-item\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"DanhSachTheoDanhMucServlet?maDanhMuc=");
      out.print(danhMuc.getMaDanhMuc());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"header__category-link\"> <i class=\"fa fa-book\"></i>");
      out.print(danhMuc.getTenDanhMuc());
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sub__menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub__menu-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub__menu-inner\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display: grid; width: 100%; height: 100%; grid-template-columns: repeat(3, 1fr); grid-template-rows: repeat(3, 1fr);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											int soNhom = 0;

												for (NhomTheLoaiBEAN nhomTheLoai : nhomTheLoaiBean) {
													if (nhomTheLoai.getMaDanhMuc() == danhMuc.getMaDanhMuc()) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"sub__menu-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"SachTheoNhomTheLoaiServlet?maNhomTheLoai=");
      out.print(nhomTheLoai.getMaNhomTheLoai() );
      out.write("\" style=\"color: #000\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t>");
      out.print(nhomTheLoai.getTenNhomTheLoai());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"sub__menu-list\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													int soTheLoai = 0;
																for (TheLoaiBEAN theLoai : theLoaiBean) {
																	if (theLoai.getMaNhomTheLoai() == nhomTheLoai.getMaNhomTheLoai()) {
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"sub__menu-item\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"SachTheoTheLoaiServlet?maTheLoai=");
      out.print(theLoai.getMaTheLoai());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"sub__menu-link\">");
      out.print(theLoai.getTenTheLoai());
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													soTheLoai += 1;
																	}

																	if (soTheLoai == 3) {
																		out.print(
																				"<a href='' style='color: #ff5800;font-size: 12px;border-bottom: 1px solid #ff5800;'> Xem thêm</a>");
																		break;
																	}
																}
												
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											soNhom++;
													}

													if (soNhom == 9) {
														out.print(
																"<a href='' style='color: #ff5800;font-size: 12px;border-bottom: 1px solid #ff5800;'> Xem thêm</a>");
														break;
													}
												}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub__menu-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"image/menu_Sach_trong_nuoc.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"header__menu\">\r\n");
      out.write("\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"header__menu-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"header__menu-item\"><a href=\"/KhoSach\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"header__menu-link\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"header__menu-item\"><a href=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"header__menu-link\">Giới thiệu</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"header__menu-item\"><a href=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"header__menu-link\">Khuyến mãi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"header__menu-item\"><a href=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"header__menu-link\">Liên hệ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");

							    if(session.getAttribute("maKhachHang")!=null){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"header__menu-item\"><a href=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"header__menu-link\">Tài khoản</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul style=\"box-shadow: 0 3px 10px rgba(34, 25, 25, 0.4);\" class=\"header__menu-list-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"Thongtincanhan\" class=\"header__menu-link-sub\">Thông tin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcá nhân</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"DangXuatServlet\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"header__menu-link-sub\">Đăng Xuất</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							    }
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div class=\"container mt-3\">\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\" top-my-account ty-float-right\">\r\n");
      out.write("\t\t\t\t\t<div id=\"account_info_154\" class=\"popup popup_user hidden active\">\r\n");
      out.write("\t\t\t\t\t\t<button style=\"background: #ff5a01\" class=\"btnClose\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t<i style=\"font-size: 25px; color: #fff;\" class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"popup__content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"popup__img active\" id=\"login1\" data-value=\"login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"title-login\">Đăng nhập</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"desc-login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tChào mừng bạn quay lại.<br>Đăng nhập để theo dõi đơn hàng,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tđánh dấu sản phẩm yêu thích, cập nhật thông tin, và nhận nhiều\r\n");
      out.write("\t\t\t\t\t\t\t\t\tưu đãi hấp dẫn từ Kho Sach.\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"popup__img\" id=\"resigter1\" data-value=\"register\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"title-login\">Tạo tài khoản</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"desc-login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tChào mừng bạn đến tới Kho Sach.<br>Tạo tài khoản để trở\r\n");
      out.write("\t\t\t\t\t\t\t\t\tthành thành viên, theo dõi đơn hàng, cập nhật thông tin, và\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnhận nhiều ưu đãi từ Kho Sach.\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"popup__body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"popup__header nav nav-tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#login\" role=\"tab\" id=\"btn_login\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"nav-link active button\" aria-selected=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-toggle=\"tab\">Đăng nhập</a> <a style=\"width: 177px; height: 44px;\" href=\"#resigter\" role=\"tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"btn_resigter\" aria-selected=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"nav-link button\" data-toggle=\"tab\">Tạo tài khoản</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tab__content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"popup__body__inner show active\" role=\"tabpanel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form name=\"popup_login_form\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmethod=\"post\" class=\"cm-processed-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"return_url\" value=\"index.php\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"redirect_url\" value=\"index.php\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"popup__form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label style=\"width: 95px\" for=\"user_loginmain_login\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"cm-required\">Email/SĐT</label> <input id=\"userName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 408px\" value=\"\" id=\"user_loginmain_login\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"userName\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Nhập số điện thoại or Email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tautocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label style=\"width: 95px\" for=\"ppsw_main_login\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"cm-required\">Mật khẩu</label> <input id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 408px\" id=\"ppsw_main_login\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" placeholder=\"Nhập mật khẩu đăng nhập\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"32\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-danger\" style=\"margin-left:97px\" id=\"result\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"button-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"popup__forgot\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"popup__checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"remember_me\" type=\"checkbox\" id=\"remember\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"Y\"> <label for=\"remember\">Ghi nhớ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tđăng nhập</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"forgot\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tBạn quên mật khẩu đăng nhập? Nhấn vào <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"https://nhanvan.vn/quen-mat-khau.html\">đây</a>.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button id=\"subDangNhap\" class=\"button btn-orrange\" type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dispatch[auth.login]\">Đăng nhập</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"popup__body__inner\" role=\"tabpanel\" id=\"resigter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form name=\"profiles_register_form\" method=\"POST\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"cm-processed-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"popup__form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"full_name\" class=\"cm-required\">Họ tên</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"full_name\" name=\"hoten\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" placeholder=\"Họ và tên*\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-danger\" style=\"margin-left: 150px\" id=\"resultempty\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"full_name\" class=\"cm-required\">Tên Đăng Nhập</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"user_name\" name=\"tendn\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" placeholder=\"Tên đăng nhập*\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-danger\" style=\"margin-left: 150px\" id=\"resultusername\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pphone\" class=\"cm-required cm-phone\">SĐT</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"pphone\" name=\"sdt\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Số điện thoại*\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-danger\" style=\"margin-left: 150px\" id=\"resultphone\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pemail\" class=\"cm-email cm-required hidden\">E-mail</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"pemail\" value=\"\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"Email của bạn\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-danger\" style=\"margin-left: 150px\" id=\"resultemail\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"ppassword1\" class=\"cm-required cm-password\">Mật\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tkhẩu</label> <input type=\"password\" id=\"ppassword1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Mật khẩu*\" name=\"matkhau1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"32\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"cm-autocomplete-off\" value=\"\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-danger\" style=\"margin-left: 150px\" id=\"resultMK1\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"ppassword2\" class=\"cm-required cm-password\">Xác\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tnhận mật khẩu</label> <input type=\"password\" id=\"ppassword2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Mật khẩu*\" name=\"matkhau2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"32\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"cm-autocomplete-off\" value=\"\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-danger\" style=\"margin-left: 150px\" id=\"resultMK2\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"gioitinh\" class=\"cm-required\">Giới tính</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"popup__checkbox popup__checkbox--inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radioGroup\" value=\"male\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"male\" required> <label for=\"male\">Nam</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"radio\" name=\"radioGroup\" value=\"female\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"female\" required> <label for=\"female\">Nữ</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"ngaysinh\">Ngày sinh</label> <input value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"ngaysinh\" type=\"date\" id=\"ngaySinh\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Ngày sinh của bạn\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"button-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"popup__checkbox popup__checkbox--italic\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"italic\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfor=\"italic\">Nhận thông báo và các khuyến mãi từ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tKho Sach qua mail</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"popup__register\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"button btn-orrange\" type=\"submit\" id=\"subDangKy\">Đăng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tKý</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--account_info_154-->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Inline script moved to the bottom of the page -->\r\n");
      out.write("\t\t\t\t\t<div class=\"mask active\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- End of header -->");
      out.write("\r\n");
      out.write("<section class=\"product-detail bg-gray py-5\"\r\n");
      out.write("\tstyle=\"padding-top: 0px !important\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav aria-label=\"breadcrumb\">\r\n");
      out.write("\t\t\t<ol class=\"breadcrumb text-capitalize bg-white\">\r\n");
      out.write("\t\t\t\t<li class=\"breadcrumb-item\"><a style=\"color: #000\" href=\"/KhoSach\"\r\n");
      out.write("\t\t\t\t\tclass=\"text-purple font-15pt\">trang chủ</a></li>\r\n");
      out.write("\t\t\t\t<li style=\"color: #ff5800\" class=\"breadcrumb-item active font-15pt\">giỏ hàng</li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 col-md-12 col-lg-12\">\r\n");
      out.write("\t\t\t\t");

					if (gio.isEmpty()) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"cart-empty text-center\">\r\n");
      out.write("\t\t\t\t\t<img src=\"image/cart-empty.png\" class=\"img-fluid cart-empty-img\">\r\n");
      out.write("\t\t\t\t\t<div class=\"font-title my-2 text-capitalize\">giỏ hàng trống</div>\r\n");
      out.write("\t\t\t\t\t<a style=\"background: #ff5800;\" href=\"/KhoSach\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-purple font-title my-2 text-uppercase\">mua sản\r\n");
      out.write("\t\t\t\t\t\tphẩm</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"nav-table-item nav-table-left position-absolute text-center\">\r\n");
      out.write("\t\t\t\t\t<i class=\"far fa-chevron-left fa-2x text-white\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"nav-table-item nav-table-right position-absolute text-center\">\r\n");
      out.write("\t\t\t\t\t<i class=\"far fa-chevron-right fa-2x text-white\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-scroll position-relative\"\r\n");
      out.write("\t\t\t\t\tstyle=\"overflow-x: auto;\" id=\"listCart\">\r\n");
      out.write("\t\t\t\t\t<table id=\"table\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"table table-hover table-striped bg-white table-bordered table-cart mb-0\"\r\n");
      out.write("\t\t\t\t\t\tid=\"Cart\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"font-title font-15pt font-weight-normal nowrap-text\">Tên\r\n");
      out.write("\t\t\t\t\t\t\t\tsản phẩm</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"font-title font-15pt font-weight-normal nowrap-text\">Hình\r\n");
      out.write("\t\t\t\t\t\t\t\tảnh</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"font-title font-15pt font-weight-normal nowrap-text\">Số\r\n");
      out.write("\t\t\t\t\t\t\t\tlượng</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"font-title font-15pt font-weight-normal nowrap-text\">Giá</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"font-title font-15pt font-weight-normal nowrap-text\">Thành\r\n");
      out.write("\t\t\t\t\t\t\t\ttiền</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"font-title font-15pt font-weight-normal nowrap-text\">Thao\r\n");
      out.write("\t\t\t\t\t\t\t\ttác</th>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody class=\"font-15pt\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (GioHangBEAN gh : gio) {
								TongTien = TongTien + (gh.getGia() * gh.getSoLuong());
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr id=\"tr");
      out.print(gh.getMaSach());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"text-align: center\">");
      out.print(gh.getTenSach());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"text-align: center\" class=\"table-product-img\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"image/");
      out.print(gh.getAnh());
      out.write("\" style=\"width: 40px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"display: inline-flex;\" class=\"cart-plus-minus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"GiamSL(");
      out.print(gh.getMaSach());
      out.write(")\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"dec qtybutton btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: 3px; background: #ff5800;\">-</a> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"sl");
      out.print(gh.getMaSach());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"background: #fff; width: 50px; padding: 5px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"cart-plus-minus-box\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonkeypress=\"updateCart(");
      out.print(gh.getMaSach());
      out.write(")\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(gh.getSoLuong());
      out.write("\" inputmode=\"numberic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"slc");
      out.print(gh.getMaSach() );
      out.write("\" type=\"hidden\" value=\"");
      out.print(gh.getSoLuong());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"slMax");
      out.print(gh.getMaSach() );
      out.write("\" type=\"hidden\" value=\"");
      out.print(gh.getSoLuongMax());
      out.write("\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"TangSL(");
      out.print(gh.getMaSach());
      out.write(")\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"dec qtybutton btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-left: 3px; background: #ff5800;\">+</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"gia");
      out.print(gh.getMaSach());
      out.write("\" style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"nowrap-text\">");
      out.print(gh.getGia());
      out.write(" đ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"tongGia");
      out.print(gh.getMaSach());
      out.write("\" style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"nowrap-text\">");
      out.print(gh.getSoLuong() * gh.getGia());
      out.write(" đ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"text-align: center\" class=\"text-danger font-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"del-product\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"xoaSach(");
      out.print(gh.getMaSach() );
      out.write(")\" style=\"color:#fff;cursor: pointer;\"\tclass=\"btn btn-sm btn-danger\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-trash-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\" class=\"text-right text-danger font-title\">Tổng\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttiền</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"tongTien\" style=\"text-align: center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"text-danger font-title\">");
      out.print(TongTien);
      out.write(" đ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"text-align: center\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"xoaSachAll()\" style=\"color:#fff;cursor: pointer;\" name=\"deleteAllCart\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-sm btn-danger text-capitalize\">Xóa giỏ hàng</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"mua\" class=\"text-right btn-action-cart\" style=\"padding-top: 12px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/KhoSach\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-warning text-uppercase font-title mr-3 border-0\">tiếp\r\n");
      out.write("\t\t\t\t\t\ttục mua hàng</a>\r\n");
      out.write("\t\t\t\t\t");

						if (session.getAttribute("maKhachHang") != null) {
					
      out.write("<a href=\"Dathang\" style=\"background: #ff5800;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-purple text-uppercase font-title border-0\">tiến\r\n");
      out.write("\t\t\t\t\t\thành đặt hàng</a>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a id=\"myBtn1\" style=\"background: #ff5800;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-purple text-uppercase font-title border-0 header__wrapper-link\">tiến\r\n");
      out.write("\t\t\t\t\t\thành đặt hàng</a>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer class=\"dark\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\"><img src=\"image/logo.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t<p>Cửa hàng phân phối sách hàng đầu việt nam</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"\"><img src=\"images/ft-img-2.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"list-ft\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Giới thiệu</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Về chúng tôi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Hình thức mua hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Hình thức thanh toán</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Chính sách bảo mật</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Tư vấn</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"list-ft\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Thông tin trợ giúp</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Hướng dẫn mua hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Vận chuyển và giao hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Đổi và trả hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Chính sách bảo hành</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"list-ft\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Thông tin trợ giúp</h4>\r\n");
      out.write("\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-map-marker-alt\"></i>&ensp;&nbsp;<span>Số 1\r\n");
      out.write("\t\t\t\t\t\t\tNam kỳ khởi nghĩa</span> <br> <i class=\"fas fa-phone-alt\"></i>&ensp;&nbsp;<span>CSKH:\r\n");
      out.write("\t\t\t\t\t\t\t0981.926.011 - 0914.666.512</span> <br> <i class=\"fas fa-envelope\"></i>&ensp;&nbsp;<span>lienhe@gmail.com</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footer-bot\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a href=\"/\">Trang chủ</a> /<a href=\"/gioi-thieu-1\">Giới thiệu</a> /<a\r\n");
      out.write("\t\t\t\thref=\"/tin-khuyen-mai-kangaroo\">Khuyến mãi</a> /<a\r\n");
      out.write("\t\t\t\thref=\"/tin-thoi-su-kangaroo\">Liên hệ</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-half text-center\">www.khoasach.vn</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- End of footer !-->\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"productModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\tstyle=\"overflow-y: hidden;\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button style=\"outline: 0\" type=\"button\" class=\"close\"\r\n");
      out.write("\t\t\t\t\tdata-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-product clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product-images\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/product-1.jpg\" alt=\"\" id=\"zoom_03\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumnail pt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"thumnail-item owl-carousel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" data-image=\"images/product-1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-zoom-image=\"images/product-1.jpg\"><img class=\"zoom_03\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/product-1.jpg\" alt=\"\"></a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-image=\"img/1.jpg\" data-zoom-image=\"img/1.jpg\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"zoom_03\" src=\"img/1.jpg\" alt=\"\"></a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-image=\"img/2.jpg\" data-zoom-image=\"img/2.jpg\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"zoom_03\" src=\"img/2.jpg\" alt=\"\"></a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-image=\"img/3.jpg\" data-zoom-image=\"img/3.jpg\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"zoom_03\" src=\"img/3.jpg\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- .product-images -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"product-info\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Máy lọc nước Kangaroo Hydrogen KG100HC vỏ tủ VTU</h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"price-box-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"s-price-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"new-price\"> 8.290.000₫ </span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"old-price\">11.500.000₫</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"see-all\">Xem tất cả tính năng</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"quick-add-to-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"numbers-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"number\" id=\"french-hens\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"single_add_to_cart_button\" type=\"submit\">Thêm\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvào giỏ</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"quick-desc\">Máy lọc nước Kangaroo Hydrogen\r\n");
      out.write("\t\t\t\t\t\t\tKG100HC 10 lõi vỏ tủ VTU trụ tròn đen Sự kết hợp hoàn hảo giữa\r\n");
      out.write("\t\t\t\t\t\t\tphong cách thiết kế Châu Âu với quan niệm phong thủy Á Đông tạo\r\n");
      out.write("\t\t\t\t\t\t\tnên một kiệt tác về thiết kế, một nét chấm phá đặc sắc trong\r\n");
      out.write("\t\t\t\t\t\t\tkhông gian thiết ...</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- .product-info -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- .modal-product -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- .modal-body -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- .modal-content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- .modal-dialog -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END Modal -->\r\n");
      out.write("<!-- Load Facebook SDK for JavaScript -->\r\n");
      out.write("<!-- Load Facebook SDK for JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"\" id=\"scrollUp\"></a>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/plugin.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.elevateZoom-3.0.8.min.js\"></script>\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("<script src=\"js/search.js\"></script>\r\n");
      out.write("<script src=\"js/doimatkhau.js\"></script>\r\n");
      out.write("<script src=\"js/TangSLGioHang.js\"></script>\r\n");
      out.write("<script src=\"js/checkDangNhap.js\"></script>\r\n");
      out.write("<script src=\"js/validateregister.js\"></script>\r\n");
      out.write("<script src=\"js/huydonhang.js\"></script>\r\n");
      out.write("<script src=\"js/binhluan.js\"></script>\r\n");
      out.write("<script src=\"js/pagination.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("  $(\"#myBtn\").click(function(){\r\n");
      out.write("    $(\"#myModal\").modal();\r\n");
      out.write("  });\r\n");
      out.write("  $(\"#myBtn1\").click(function(){\r\n");
      out.write("\t    $(\"#myModal\").modal();\r\n");
      out.write("\t  });\r\n");
      out.write("  $('#btn_login').click(function(){\r\n");
      out.write("      $('#resigter1').removeClass(\"active\");\r\n");
      out.write("      $('#login1').addClass(\"active\");\r\n");
      out.write("  });\r\n");
      out.write("  $('#btn_resigter').click(function(){\r\n");
      out.write("      $('#login1').removeClass(\"active\");\r\n");
      out.write("      $('#resigter1').addClass(\"active\");\r\n");
      out.write("  });\r\n");
      out.write("  /* check so luong input  */\r\n");
      out.write("  $(\"#qty_count\").change(function(){\r\n");
      out.write("\t  \t var soLuong = parseInt($('#qty_count').val(),10);\r\n");
      out.write("\t      if(soLuong==0){\r\n");
      out.write("\t\t    \t$(\"#qty_count\").val(\"1\");\r\n");
      out.write("\t     }\r\n");
      out.write("\t});\r\n");
      out.write(" /*  <!-- Tăng số lượng\r\n");
      out.write("//--> */\r\n");
      out.write("\r\n");
      out.write("  $(\"#qty_count_tru\").click(function(){\r\n");
      out.write("  \t var soLuong = parseInt($('#qty_count').val(),10);\r\n");
      out.write("      if(soLuong>1){\r\n");
      out.write("\t    \t$(\"#qty_count\").val(soLuong-1);\r\n");
      out.write("     }\r\n");
      out.write("\t  });\r\n");
      out.write("\t  $(\"#qty_count_cong\").click(function(){\r\n");
      out.write("\t     var soLuong = parseInt($('#qty_count').val(),10)+1;\r\n");
      out.write("\t    $(\"#qty_count\").val(soLuong);\r\n");
      out.write("\t  });\r\n");
      out.write("\t  /* cập nhập thông tin */\r\n");
      out.write("\t    $(document).ready(function(){\r\n");
      out.write("\t        $(\"#editInfo\").click(function(){\r\n");
      out.write("\t          $(\"#editInfoModal\").modal();\r\n");
      out.write("\t      });\r\n");
      out.write("\t    });\r\n");
      out.write("\t    function calcRate(r) {\r\n");
      out.write("\t    \t const f = ~~r,//Tương tự Math.floor(r)\r\n");
      out.write("\t    \t id = 'star' + f + (r % f ? 'half' : '')\r\n");
      out.write("\t    \t id && (document.getElementById(id).checked = !0)\r\n");
      out.write("\t    \t};\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
